name: "Artifact Management"

on:
  workflow_dispatch:
  schedule:
    - cron: '15 8 1 * *'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses:  dscabsa/purge-artifacts-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days
          

