name: "Link Check"

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
    
jobs:
  link-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: link-check
        run: nix develop -c make -C docs/ linkcheckdiff SPHINXOPTS="--keep-going"

      - name: Arhive Log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: LINKCHECK--1
          path: docs/build/linkcheckdiff/output.json
          retention-days: 7
